# Generated by Django 4.2.2 on 2023-06-27 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='salery',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
