# Generated by Django 4.2.2 on 2023-06-28 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_students_salery'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='services',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
