# Generated by Django 4.2.2 on 2023-06-30 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_students_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='phone',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
